### ISSUE TITLE
After being poisoned wears off, !Cure Poison! is shown instead of You feel less sick

### ISSUE THREAD

**Issue by pierrewery** [mattgodbolt/xania#209] opened 2020-09-04 21:47 UTC
During a fight I saw !Cure Poison! instead of You feel less sick. I don't have cure Poison so wasn't me doing it.

**Comment by mattgodbolt** [comment] 2020-09-04 21:51
That's the `msg_off` for the `skill_table`. I wonder what's going on there!

**Comment by mattgodbolt** [comment] 2020-09-04 21:51
Ah! I refactored this. THis is a new definition of "refactor" which actually means "broke terribly"

**Comment by mattgodbolt** [comment] 2020-09-04 22:07
Really weird: are you _certain_ it was `!Cure Poison!` ?

Tried to repro and got:
```
You feel less sick.
```

I wonder what spell is being cast on you? Is there any chance you have the log up still? We know there's possibly a problem with the spells maybe being a bit out of sync (see #207 ) so it would be helpful!

Failing that: who were you fighting ?

**Comment by mattgodbolt** [comment] 2020-09-04 22:10
It could be `dispel magic`! the mob might have cast it on you...checking. I also "refactored" that

**Comment by mattgodbolt** [comment] 2020-09-04 22:14
Ah probably not. Fight was against the king in gnome village. so will try to repro later.

**Comment by mattgodbolt** [comment] 2020-09-05 15:32
The king has `spec_cast_mage`; investigating.

**Comment by snellers** [comment] 2020-09-05 16:38
This is fixed now, it was a regression due to #194 which is now rolled back. If you got affected by 'poison' e.g. by eating guts, then disconnected then logged in again, the pfile loader would misinterpret the poison affect line as 'cure poison'. This would then decay over several ticks and show the placeholder fade message.

**Closed by snellers** 2020-09-05 16:38 UTC
Labels: bug
